version: '3.8'

services:
  soap-service:
    image: 'pet-soap-service:latest'
    build: ./petclinic-service
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    volumes:
      - ./postgres/sql-init:/docker-entrypoint-initdb.d
      - ./postgres/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=petclinic
      - PGDATA=/var/lib/postgresql/data/pgdata
